<!DOCTYPE html>
<html>
<head>
	<title>
		ABOUT US
	</title>

	 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  <style >
    
        @media screen and (max-width: 1000px){
        #foot{
              
              font-size: 45px;
        }}

      </style>
</head>
<body>

	<section>
<div class="container-fluid text-white bg-dark pl-0 pr-0 ">
 
    <nav class="navbar  navbar-expand-lg navbar-dark  ">
  <a class="navbar-brand" href="bootstrap.php">NEWSROOM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav justify-content-end ml-auto">
      <li class="nav-item ">
        <a class="nav-link" href="bootstrap.php">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="ABOUTUS.php">ABOUT US</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="national.php">NATIONAL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="international.php">INTERNATIONAL</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="sports.php">SPORTS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="contactus.php">CONTACT US</a>
      </li>
      
     
  </div>
</nav>

</section>

<!--nav end-->

<section>
	<div class="container bg-light pl-0 pr-0 ">
	<div class="col-sm-12 " style="border: 5px solid;"><h1 class="text-center mt-4 mb-4" >ABOUT WORK</h1> </div>

	<div class="col-sm-12 "></div>
</section>

 <!-- Footer -->
<footer class="page-footer font-small indigo bg-dark mt-2" >

  <!-- Footer Links -->
  <div class="container text-center ">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4 text-white" id="foot">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="bootstrap.php">HOME</a>
          </li>
          <a href="aboutus.php">ABOUT US</a>
          </li>
          <li>
            <a href="national.php">NATIONAL</a>
          </li>
          <li>
            <a href="international.php">INTERNATIONAL</a>
          </li>
          <li>
            <a href="sports.php">SPORTS</a>
          </li>
          <a href="contactus.php">CONTACT US</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Links -->
        <h4 class="font-weight-bold text-uppercase text-white mt-3 mb-4">Social Media Links</h4>

        <ul class="list-unstyled">
          <li>
            <img src="fb.png" style="height: 30px;">
            <a href="https://www.facebook.com/" class="ml-2">Join with us on facebook</a>
          </li>
          <li  class="mt-3">
            <img src="twitter.png" class="pr-4" style="height: 25px;">
            <a href="https://twitter.com/explore">Join with us on twitter</a>
          </li>
          <li class="mt-3">
            <img src="insta.png" style="height: 30px;">
            <a href="https://www.instagram.com/?hl=en" ">Join with us on instagram</a>
          </li>
        
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">
        <h3 class="text-white mt-3">CONTACT FORM</h3>

       <form action="" class="was-validated">
    <div class="form-group">
      <label for="uname">Username:
      <input type="text" class="form-control" id="uname" placeholder="Enter username" name="uname" required></label>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>
    <div class="form-group">
      <label for="pwd">Password:
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required></label>
      <div class="valid-feedback">Valid.</div>
      <div class="invalid-feedback">Please fill out this field.</div>
    </div>
    <div class="form-group form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Check this checkbox to continue.</div>
      </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>


     

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-white py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</body>
</html>